name: 'Giftwrap Action'
description: 'Provide a description here'
author: 'ForAllSecure'
inputs:
  mayhem-url:
    description: URL pointing to your Mayhem instance
    required: true
  mayhem-token:
    description: Personal API token for authenticating to Mayhem
    required: true
  github-token:
    description: Github token for posting feedback
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
